from __future__ import annotations

import os
import json
import argparse
from pathlib import Path

import mlflow
from mlflow.tracking import MlflowClient


def load_gate_result(path: str) -> dict:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Gate result file not found: {path}")
    return json.loads(p.read_text())


def main():
    ap = argparse.ArgumentParser(description="Register and stage a model only if evaluation gate passed.")
    ap.add_argument("--run-id", required=True)
    ap.add_argument("--model-name", default="ticket-router")
    ap.add_argument("--artifact-path", default="model")
    ap.add_argument(
        "--gate-file",
        default="reports/eval_gate.json",
        help="Path to evaluation gate JSON generated by src/evaluate.py",
    )
    args = ap.parse_args()

    tracking_uri = os.environ.get("MLFLOW_TRACKING_URI")
    if not tracking_uri:
        raise SystemExit("Missing MLFLOW_TRACKING_URI env var")

    mlflow.set_tracking_uri(tracking_uri)
    client = MlflowClient()

    gate = load_gate_result(args.gate_file)

    if gate.get("run_id") != args.run_id:
        raise SystemExit(
            f"Gate file run_id {gate.get('run_id')} does not match requested run_id {args.run_id}"
        )

    if not gate.get("passed", False):
        raise SystemExit(
            f"Model did not pass evaluation gate. Reasons: {gate.get('reasons', [])}"
        )

    run = client.get_run(args.run_id)

    # Ensure registered model exists
    try:
        client.get_registered_model(args.model_name)
    except Exception:
        client.create_registered_model(args.model_name)
        print(f"✅ Created registered model: {args.model_name}")

    source = f"{run.info.artifact_uri}/{args.artifact_path}"

    mv = client.create_model_version(
        name=args.model_name,
        source=source,
        run_id=args.run_id,
    )

    print(f"✅ Registered {args.model_name} v{mv.version} from run {args.run_id}")
    print(f"   source: {source}")

    client.transition_model_version_stage(
        name=args.model_name,
        version=mv.version,
        stage="Staging",
        archive_existing_versions=False,
    )

    print(f"✅ Promoted to Staging: {args.model_name} v{mv.version}")


if __name__ == "__main__":
    main()